# Generated by Django 4.2.18 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
