# Generated by Django 4.2.18 on 2025-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userdata_age_remove_userdata_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='userdata',
            name='coordinates_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='coordinates_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
